### ISSUE TITLE
application error event viewer

### ISSUE THREAD

**Issue by alexeik** [fifonik/FFMetrics#134]
After put filepath it starting to analize and then crashes...
all versions :release and last beta.

Application: FFMetrics.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.Windows.DependencyObject.ValidateSources(System.Windows.DependencyObject, System.Windows.DependencySource[], System.Windows.Expression)
   at System.Windows.Expression.ChangeSources(System.Windows.DependencyObject, System.Windows.DependencyProperty, System.Windows.DependencySource[])
   at System.Windows.Data.BindingExpressionBase.ChangeSources(MS.Internal.Data.WeakDependencySource[])
   at MS.Internal.Data.ClrBindingWorker.ReplaceDependencySources()
   at MS.Internal.Data.ClrBindingWorker.NewValueAvailable(Boolean, Boolean, Boolean)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32, System.ComponentModel.ICollectionView, System.Object, Boolean)
   at MS.Internal.Data.PropertyPathWorker.RefreshValue()
   at MS.Internal.Data.ClrBindingWorker.ScheduleTransferOperation(System.Object)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at FFMetrics.App.Main()

**Comment by alexeik** [comment]
hmm
after renamed conf.example to conf and set tempdir to real 
it works now after pasting file path in Reference block.

**Comment by fifonik** [comment]
If this issue is re-producable on your system, it would be nice if you try to find what causing the crash, so I will be able to fix it.
It is possible that the issue caused by inability to save something in temp dir. If this is the case, specifying --temp="c:\path\to\temp" should help.

**Comment by alexeik** [comment]
> after renamed conf.example to conf and set tempdir to real

yes it is :)

**Comment by fifonik** [comment]
I wish I undesrtand what do you mean.

**Comment by fifonik** [comment]
Re-produced and adding more checks on startup. Thanks.

**Comment by fifonik** [comment]
Temp dir existance and access implemented in 1.5.0 beta 1 (just released).
